export {
  uuidSchema,
  optionalUuid,
  createAssessmentSchema,
  updateAssessmentSchema,
  assessmentQuerySchema,
  createGradeSchema,
  updateGradeSchema,
  createScheduleSchema,
  updateScheduleSchema,
  scheduleQuerySchema,
  createResultSchema,
  updateResultSchema,
  resultQuerySchema,
  idParamsSchema,
  assessmentIdParamsSchema,
  gradeParamsSchema,
  classIdParamsSchema,
  printPautaQuerySchema,
  printScheduleQuerySchema,
} from '../../../src/modules/schedules-assessments/schemas';