export {
  uuidSchema,
  optionalUuid,
  createAssessmentSchema,
  updateAssessmentSchema,
  assessmentQuerySchema,
  createGradeSchema,
  updateGradeSchema,
  createScheduleSchema,
  updateScheduleSchema,
  scheduleQuerySchema,
  createResultSchema,
  updateResultSchema,
  resultQuerySchema,
  calculationMethodSchema,
  roundingSchema,
  calculationItemSchema,
  calculationComponentSchema,
  calculationInputSchema,
  idParamsSchema,
  assessmentIdParamsSchema,
  gradeParamsSchema,
  classIdParamsSchema,
  printPautaQuerySchema,
  printScheduleQuerySchema,
} from '../../../src/modules/schedules-assessments/schemas';